FROM bitnami/spark:3.5.5

USER root
WORKDIR /app

RUN install_packages python3 python3-pip

COPY preprocessing/subway_streaming.py /app/preprocessing/subway_streaming.py
COPY utils /app/utils
COPY requirements.txt /app/requirements.txt

RUN pip3 install --no-cache-dir -r /app/requirements.txt

ENV PYTHONPATH=/app

CMD ["spark-submit",     "--master", "spark://spark-master:7077",     "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.5",     "/app/preprocessing/subway_streaming.py"]
