FROM apache/spark:3.5.1

USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY preprocessing/outbreak_streaming.py /app/
COPY preprocessing/emergency_streaming.py /app/
COPY utils/ /app/utils/

RUN chown -R spark:spark /app

RUN pip3 install --no-cache-dir \
    redis \
    mysql-connector-python

ENV PYTHONPATH=/app
ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3

USER spark