FROM python:3.11-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

RUN pip install --no-cache-dir \
    boto3 \
    botocore \
    kafka-python \
    mysql-connector-python \
    redis \
    requests \
    python-dotenv

COPY . /app

#CMD ["python", "consumers/s3_raw_consumer.py"]