FROM apache/airflow:2.8.4-python3.9

# airflow 사용자로 유지
USER airflow

# 추가 패키지 설치 (Airflow 공식 권장 방식)
#ENV _PIP_ADDITIONAL_REQUIREMENTS="pyspark==3.5.0"

# 필요한 패키지 설치
COPY requirements.txt /requirements.txt
COPY airflow/dags /opt/airflow/dags
COPY airflow/plugins /opt/airflow/plugins
COPY preprocessing /opt/airflow/preprocessing
COPY producer /opt/airflow/producer

RUN pip install --user --no-cache-dir -r /requirements.txt

ENV PYTHONPATH=/opt/airflow/dataflow