apiVersion: v1
kind: Pod
metadata:
  name: airflow-worker
  namespace: airflow

spec:
  serviceAccountName: airflow
  restartPolicy: Never

  securityContext:
    fsGroup: 50000

  containers:
    - name: base
      image: dndjeh/navisafe-airflow:v10
      imagePullPolicy: IfNotPresent

      env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: KubernetesExecutor
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: mysql+pymysql://user:userpass@mysql.default:3306/airflow_db
        - name: AIRFLOW__CORE__FERNET_KEY
          value: 5ozw1xClhNUKElcA31BOLTCr3f8de2whokz13dLXQ1w=
        - name: PYTHONPATH
          value: /opt/airflow

      volumeMounts:
        - name: airflow-logs
          mountPath: /opt/airflow/logs


  volumes:
    - name: airflow-logs
      persistentVolumeClaim:
        claimName: airflow-logs-pvc