replicas: 1
minimumMasterNodes: 1

clusterHealthCheckParams: "wait_for_status=yellow&timeout=5s"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "1Gi"

esJavaOpts: "-Xms512m -Xmx512m"

volumeClaimTemplate:
  resources:
    requests:
      storage: 5Gi